routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/users', [App\Http\Controllers\UserController::class, 'index']);

//training
Route::get('/trainings', [App\Http\Controllers\TrainingController::class, 'index'])->name('training:index');
Route::get('/trainings/create', [App\Http\Controllers\TrainingController::class, 'create'])->name('training:create');
Route::post('/trainings/create', [App\Http\Controllers\TrainingController::class, 'store'])->name('training:store');

Route::get('/trainings/{training}', [App\Http\Controllers\TrainingController::class, 'show'])->name('training:show');
Route::get('/trainings/{training}/edit', [App\Http\Controllers\TrainingController::class, 'edit'])->name('training:edit');
Route::post('/trainings/{training}/edit', [App\Http\Controllers\TrainingController::class, 'update'])->name('training:update');
Route::get('/trainings/{training}/delete', [App\Http\Controllers\TrainingController::class, 'delete'])->name('training:delete');

Route::view('test', 'admin.layouts.main');

app/Models/Training.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Training extends Model
{
    use HasFactory;

    //define fillables for mass assignments
    protected $fillable = [
        'title', 'description', 'user_id', 'attachment'
    ];

    //One training belongs to one user
    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    //getter - return attachment url
    public function getAttachmentUrlAttribute()
    {
        return asset('storage/'.$this->attachment);
    }
}

app/Http/Controllers/TrainingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Models\Training;
use \App\Mail\TrainingCreatedMail;
use \App\Jobs\SendEmailJob;
use Storage;
use File;
Use Mail;
class TrainingController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    //show data dalam laman utama
    public function index(Request $request)
    {
        if($request->keyword != null){
            //query based on keyword
            $trainings = Training::where('title', 'LIKE', '%'.$request->keyword.'%')->orwhere('description', 'LIKE', '%'.$request->keyword.'%')->paginate(5);
        } else {
            // query all trainings from database using model
            $trainings = Training::paginate(5); //default - per page 15 if not set value
        }
        
        // return to view with all trainings
        // resources/views/trainings/index.blade.php
        return view('trainings.index', compact('trainings'));
    }

    public function create()
    {
        // return view create form to user
        return view('trainings.create');
    }

    public function store(Request $request)
    {
        // changes to all branch
        // dd($request->all());
        //store data into db

        //Method 1 - POPO - Plain Old PHP Object
        // $training = new Training();
        // $training->title = $request->title;
        // $training->description = $request->description;
        // $training->user_id = auth()->user()->id;
        // $training->save();

        //Method 2 - Mass Assignments + Relationship
        $user = auth()->user();
        $training = $user->trainings()->create($request->only('title','description','attachment'));

        //check if has attachment
        if($request->hasFile('attachment')){
            //rename
            $filename = $training->id.'-'.date("Y-m-d").'.'.$request->attachment->getClientOriginalExtension();
            //save
            $training->update(['attachment' => $filename]); //mass assignment + protected fillable
            //store file
            Storage::disk('public')->put($filename, File::get($request->attachment));
        }

        //Method 1 - Cara Junior
        //send mail
        // Mail::send('emails.training-created', [
        //     'title' => $training->title,
        //     'description' => $training->description
        // ], function ($message) {
        //     $message->to('ad@gmail.com');
        //     //$message->(auth->$user());
        //     $message->subject('Training Created: Using Inline Mail Facade');
        // });

        //Method 2 - Send Email using Mailable Class
        // Mail::to('ad@gmail.com')->send(new TrainingCreatedMail($training));
        
        //Method 3 - Send Email with Jobs
        dispatch(new SendEmailJob($training));

        //return to /trainings
        return redirect('/trainings')
            ->with([
                'alert-type' => 'alert-primary',
                'alert' => 'Your training has been saved.'
            ]);
    }

    public function show(Training $training)
    {
        $this->authorize('view', $training);

        return view('trainings.show', compact('training'));
    }

    public function edit(Training $training)
    {
        $this->authorize('update', $training);

        return view('trainings.edit', compact('training'));
    }

    public function update(Training $training, Request $request)
    {
        // dd($request->all());
        //update data from form to db

        // Method 1 - POPO
        // $training->title = $request->title;
        // $training->description = $request->description;
        // $training->save();

        //Method 2 - Mass Assignments
        $training->update($request->only('title','description'));

        //return to /trainings
        return redirect()
            ->route('training:index')
            ->with([
                'alert-type' => 'alert-success',
                'alert' => 'Your training has been updated.'
            ]);
    }

    public function delete(Training $training)
    {
        $this->authorize('delete', $training);
        if ($training->attachment != null){
            Storage::disk('public')->delete($training->attachment);
        }
        //delete data from db
        $training->delete();
        //return to /trainings
        return redirect()->route('training:index')
        ->with([
            'alert-type' => 'alert-danger',
            'alert' => 'Your training has been deleted.'
        ]);
    }
}

resources/views/trainings/create.blade.php
@extends('admin.layouts.main')

@section('content')
<div class="container-fluid">
    <h1 class="mt-4">Create Training</h1>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Training Create Form') }}</div>
                <div class="card-body">

                        <form action="" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label>Title</label>
                                <input type="text" name="title" class="form-control">
                            </div>
    
                            <div class="form-group">
                                <label>Description</label>
                                <textarea name="description" cols="20" rows="5" class="form-control"></textarea>
                            </div>

                            <div class="form-group">
                                <label>Upload Picture</label>
                                <input type="file" name="attachment" class="form-control">
                            </div>
    
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Store My Training</button>
                            </div>
                        </form>
                        
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/trainings/edit.blade.php
@extends('admin.layouts.main')
@section('content')
<div class="container-fluid">
    <h1 class="mt-4">Edit Training</h1>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Edit Training') }}</div>
               
                <div class="card-body">
                    <form action="" method="POST">
                        @csrf
                        <div class="form-group">
                            <label>Title</label>
                            <input type="text" name="title" class="form-control" value="{{$training->title}}" >
                        </div>

                        <div class="form-group">
                            <label>Description</label>
                            <textarea name="description" cols="20" rows="5" class="form-control" >{{$training->description}} </textarea>
                        </div>
                        
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Update My Training</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/trainings/index.blade.php
@extends('admin.layouts.main')

@section('content')
<div class="container-fluid">
    <h1 class="mt-4">Training Module</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Training List</li>
    </ol>
    <div class="row">
        <div class="col-md-12">
            @if(session()->has('alert'))
                <div class="alert {{session()->get('alert-type')}}" role="alert">
                    {{session()->get('alert')}}
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    {{ __('My Training List') }}
                    <div class="float-right">
                        <form action="" method="">
                            <div class="input-group">
                                <input type="text" class="form-control" name="keyword" value="{{(request()->get('keyword'))}}">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">Search</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Creator</th>
                                {{-- <th>Created</th> --}}
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($trainings as $training)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$training->id}}</td>
                                    <td>{{$training->title}}</td>
                                    <td>{{$training->description}}</td>
                                    <td>{{$training->user->name}}</td>
                                    {{-- <td>{{$training->created_at}}</td> --}}
                                    <td>
                                        @can('view', $training)
                                            <a href="{{route('training:show', $training)}}" class="btn btn-primary">Show</a>
                                        @endcan
                                    </td>
                                    <td>
                                        @can('update', $training)
                                        <a href="{{route('training:edit', $training)}}" class="btn btn-success">Edit</a>
                                        @endcan
                                    </td>
                                    <td>
                                        @can('delete', $training)
                                        <a onclick="return confirm('Betul nak delete?')" href="{{route('training:delete', $training)}}" class="btn btn-danger">Delete</a>
                                        @endcan
                                    </td>
                                    
                                </tr>
                            @empty 
                                <td>No data</td>
                            @endforelse
                        </tbody>
                    </table>
                    {{
                        $trainings->appends([
                            'keyword' => request()->get('keyword')
                        ])->links()
                    }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/trainings/show.blade.php
@extends('admin.layouts.main')

@section('content')
<div class="container-fluid">
    <h1 class="mt-4">Your Training</h1>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Show Training') }}</div>
               
                <div class="card-body">
                    <div class="form-group">
                        <label>Title</label>
                        <input type="text" name="title" class="form-control" value="{{$training->title}}" readonly>
                    </div>

                    <div class="form-group">
                        <label>Description</label>
                        <textarea name="description" cols="20" rows="5" class="form-control" readonly>{{$training->description}} </textarea>
                    </div>

                    <div class="form-group">
                        {{-- <a href="{{asset('storage/'.$training->attachment)}}">View Picture</a> --}}
                        <a href="{{$training->attachment_url}}">View Picture</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
@endsection